package com.nechaev.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

// Active only when the 'prod' profile is set. Prevents the application from booting with a
// Spring-autogenerated admin password (which would be printed to stdout and could leak through
// centralized log collection). Local dev and tests run without the 'prod' profile and skip this check.
@Configuration
@Profile("prod")
public class AdminPasswordCheck {

    private static final String DEV_ONLY_PASSWORD = "dev-only";

    public AdminPasswordCheck(@Value("${spring.security.user.password:}") String password) {
        if (password == null || password.isBlank() || DEV_ONLY_PASSWORD.equals(password)) {
            throw new IllegalStateException(
                    "spring.security.user.password is using the dev-only default while running with the 'prod' profile. "
                            + "Set the SPRING_SECURITY_USER_PASSWORD environment variable before starting the app.");
        }
    }
}
